CREATE DATABASE RKDb;
GO

USE RKDb;
GO

CREATE TABLE Client (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Login NVARCHAR(255) NOT NULL,
    FullName NVARCHAR(255) NOT NULL,
    Phone NVARCHAR(50) NOT NULL,
    Email NVARCHAR(255) NOT NULL
);
GO

CREATE TABLE Service (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Name NVARCHAR(255) NOT NULL
);
GO

CREATE TABLE Invoice (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    ClientId INT NOT NULL,
    ServiceId INT NOT NULL,
    Amount DECIMAL(18, 2) NOT NULL,
    Status BIT NOT NULL,
    ReceiptNumber NVARCHAR(255) NULL,
    IssueDate DATETIME2 NOT NULL,
    DueDate DATETIME2 NOT NULL,
    PaymentDate DATETIME2 NULL,
    CONSTRAINT FK_Invoice_Client FOREIGN KEY (ClientId) REFERENCES Client(Id),
    CONSTRAINT FK_Invoice_Service FOREIGN KEY (ServiceId) REFERENCES Service(Id)
);
GO
